[package]
name = "rksuid-cli"
version = "0.1.0"
authors = ["Nicholas Harring <nharring@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rksuid = "0.2.0"
structopt = "0.2.10"
